export const products = [
  {
    id: 1,
    image1: "/1.png",
    image2: "/1.1.png",
    name: "Regal Gold-Foiled MDF Box with 2-Jar, leaf & Inside box 4-Line",
    price: "1000",
    oldPrice: "2000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 2,
    image1: "/2.png",
    image2: "/2.1.png",
    name: "NEW BALANCE 9060 TRIPLE BLACK",
    price: "1000",
    oldPrice: "1000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 3,
    image1: "/3.png",
    image2: "/3.1.png",
    name: "ON RUNNING CLOUDTILT BLACK IVORY",
    price: "1000",
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: false,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 4,
    image1: "/4.png",
    image2: "/4.1.png",
    name: "ADIDAS ULTRABOOST 22",
    price: "1000",
    oldPrice: "18,000",
    category: "FILE BOX",
    isBestSeller: true,
    isNew: true,
    discount: 20,
    colors: [],
  },
  {
    id: 5,
    image1: "/5.png",
    image2: "/5.1.png",
    name: "ON RUNNING CLOUDTILT ECLIPSE BLACK",
    price: "1000",
    oldPrice: "20,000",
    category: "FILE BOX",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 6,
    image1: "/6.png",
    image2: "/6.1.png",
    name: "ADIDAS ULTRABOOST 22",
    price: "1000",
    oldPrice: "18,000",
    category: "FILE BOX",
    isBestSeller: false,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 7,
    image1: "/7.png",
    image2: "/7.1.png",
    image3: "/7.2.png",
    image4: "/7.3.png",
    name: "ADIDAS ULTRABOOST 22",
    price: "1000",
    oldPrice: "18,000",
    category: "FILE BOX",
    isBestSeller: false,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 8,
    image1: "/8.png",
    image2: "/8.1.png",
    image3: "/8.2.png",
    name: "ADIDAS ULTRABOOST 22",
    price: "1000",
    oldPrice: "18,000",
    category: "DHOLLU",
    isBestSeller: false,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 9,
    image1: "/9.png",
    image2: "/9.1.png",
    image3: "/9.2.png",
    name: "ADIDAS ULTRABOOST 22",
    price: "1000",
    oldPrice: "18,000",
    category: "FILE BOX",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 10,
    image1: "/10.png",
    image2: "/10.1.png",
    name: "ON RUNNING CLOUDTILT BLACK IVORY",
    price: "1000",
    oldPrice: "20,000",
    category: "DHOLLU",
    isBestSeller: true,
    isNew: true,
    discount: 15,
    colors: [],
  },
  {
    id: 11,
    image1: "/11.png",
    image2: "/11.1.png",
    name: "ON RUNNING CLOUDTILT BLACK IVORY",
    price: "1000",
    oldPrice: "20,000",
    category: "DHOLLU",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 12,
    image1: "/12.png",
    image2: "/12.1.png",
    name: "ON RUNNING CLOUDTILT BLACK IVORY",
    price: "1000",
    oldPrice: "20,000",
    category: "DHOLLU",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 13, 
    image1: "/13.png",
    image2: "/13.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
];