export const products = [
  {
    id: 1,
    image1: "/1.png",
    image2: "/1.1.png",
    name: "Noor-e-Baraat Box",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    price: "1000",
    oldPrice: "2000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 2,
    image1: "/2.png",
    image2: "/2.1.png",
    name: "The Peacock Royale Box",
    price: "400",
    oldPrice: "1000",
    category: "HAMPER BOX",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
    pricing: {
      25: 400,
      50: 300,
      100: 200,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
  },
  {
    id: 3,
    image1: "/3.png",
    image2: "/3.1.png",
    name: "The Royal Darbaar Box",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "SWEETS BOX",
    isBestSeller: false,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 4,
    image1: "/4.png",
    image2: "/4.1.png",
    name: "Zareen Khazana Box",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "18,000",
    category: "FILE BOX",
    isBestSeller: true,
    isNew: true,
    discount: 20,
    colors: [],
  },
  {
    id: 5,
    image1: "/5.png",
    image2: "/5.1.png",
    name: "The Blossom Box",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "CAKE BOX",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 6,
    image1: "/6.png",
    image2: "/6.1.png",
    name: "The Heritage Emerald Box",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "18,000",
    category: "PLATTER BOX",
    isBestSeller: false,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 7,
    image1: "/7.png",
    image2: "/7.1.png",
    image3: "/7.2.png",
    image4: "/7.3.png",
    name: "Baraat-e-Noor Box",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "18,000",
    category: "FILE BOX",
    isBestSeller: false,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 8,
    image1: "/8.png",
    image2: "/8.1.png",
    image3: "/8.2.png",
    name: "Noor-e-Saltanat Box",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "18,000",
    category: "DHOLLU",
    isBestSeller: false,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 9,
    image1: "/9.png",
    image2: "/9.1.png",
    image3: "/9.2.png",
    name: "ADIDAS ULTRABOOST 22",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "18,000",
    category: "FILE BOX",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 10,
    image1: "/10.png",
    image2: "/10.1.png",
    name: "The Ivory Peacock File Box",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "DHOLLU",
    isBestSeller: true,
    isNew: true,
    discount: 15,
    colors: [],
  },
  {
    id: 11,
    image1: "/11.png",
    image2: "/11.1.png",
    name: "The Sapphire Royale Box",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "DHOLLU",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 12,
    image1: "/12.png",
    image2: "/12.1.png",
    name: "ON RUNNING CLOUDTILT BLACK IVORY",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "DHOLLU",
    isBestSeller: true,
    isNew: false,
    discount: null,
    colors: [],
  },
  {
    id: 13,
    image1: "/13.png",
    image2: "/13.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 14,
    image1: "/14.png",
    image2: "/14.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 15,
    image1: "/15.png",
    image2: "/15.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 16,
    image1: "/16.png",
    image2: "/16.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 17,
    image1: "/17.png",
    image2: "/17.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 18,
    image1: "/18.png",
    image2: "/18.1.png",
    name: "Regal Mughal Garden Bhaji Box",
    price: "450",
    pricing: {
      25: 450,
      50: 410,
      100: 390,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 19,
    image1: "/19.png",
    image2: "/19.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 20,
    image1: "/20.png",
    // image2: "/13.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 21,
    image1: "/21.png",
    // image2: "/13.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 22,
    image1: "/22.png",
    // image2: "/13.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 23,
    image1: "/23.png",
    // image2: "/13.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 24,
    image1: "/24.png",
    // image2: "/13.1.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 25,
    image1: "/25.png",
    image2: "/25.1.png",
    image3: "/25.2.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 26,
    image1: "/26.png",
    image2: "/26.1.png",
    
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 27,
    image1: "/27.png",
    image2: "/27.1.png",
   
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 28,
    image1: "/28.png",
    image2: "/28.1.png",
   
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 29,
    image1: "/29.png",
    image2: "/29.1.png",
    image3: "/29.2.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 30,
    image1: "/30.png",
    image2: "/30.1.png",
    
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 31,
    image1: "/31.png",
    image2: "/31.1.png",
   
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 32,
    image1: "/32.png",
    image2: "/32.1.png",
    
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 33,
    image1: "/33.png",
    image2: "/33.1.png",
    image3: "/33.2.png",
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 34,
    image1: "/34.png",
    image2: "/34.1.png",
    
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },
  {
    id: 35,
    image1: "/35.png",
    image2: "/35.1.png",
    
    name: "ON RUNNING CLOUDTILT IVORY ALMOND (W)",
    price: "1000",
    pricing: {
      25: 1000,
      50: 900,
      100: 800,
    },
    description:
      "Premium MDF wedding box with gold-foil detailing, designed for 2 jars with elegant leaf styling and a 4-line inside layout.",
    features: [
      "Strong MDF build",
      "Gold-foil premium finish",
      "2-jar compartment",
      "Inside 4-line layout",
      "Perfect for wedding gifting",
    ],
    oldPrice: "20,000",
    category: "MDF BOX",
    isBestSeller: true,
    isNew: true,
    discount: 25,
    colors: [],
  },

];
